/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardTableRouteImport } from './routes/DashboardTable'
import { Route as DashboardRouteImport } from './routes/Dashboard'

const DashboardTableRoute = DashboardTableRouteImport.update({
  id: '/DashboardTable',
  path: '/DashboardTable',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/Dashboard': typeof DashboardRoute
  '/DashboardTable': typeof DashboardTableRoute
}
export interface FileRoutesByTo {
  '/Dashboard': typeof DashboardRoute
  '/DashboardTable': typeof DashboardTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/Dashboard': typeof DashboardRoute
  '/DashboardTable': typeof DashboardTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Dashboard' | '/DashboardTable'
  fileRoutesByTo: FileRoutesByTo
  to: '/Dashboard' | '/DashboardTable'
  id: '__root__' | '/Dashboard' | '/DashboardTable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRoute
  DashboardTableRoute: typeof DashboardTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/DashboardTable': {
      id: '/DashboardTable'
      path: '/DashboardTable'
      fullPath: '/DashboardTable'
      preLoaderRoute: typeof DashboardTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard': {
      id: '/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRoute,
  DashboardTableRoute: DashboardTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
